apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "8080"
  COOKIE_SECURE: "true"
  WEBAUTHN_RP_ID: "speedy-eboekhouden.nl"
  SMTP_PORT: "587"
  SMTP_FROM: "noreply@speedy-eboekhouden.nl"
